# Generated by Django 6.0.5 on 2026-06-28 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='student_scope',
            field=models.CharField(choices=[('all', '所有学生'), ('specified', '指定学生')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'student'}, related_name='assigned_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
